server:
  port: 8847
spring:
  aot:
    enabled: true
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: 'localhost:8848'
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - StripPrefix=1
    loadbalancer:
      eager-load:
        enabled
        clients:
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE