server:
  port: 8847
spring:
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: 'localhost:8848'
    gateway:
      discovery:
        locator:
          enabled: true
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO