jobs:
  build_and_push:
    name: Build with gradle and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Restore local.properties
        shell: bash
        run: echo 'dockerImageName=${{ env.IMAGE_NAME }}' > ./local.properties
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage
      - name: Push the image
        run: docker push ${{ env.IMAGE_NAME }}
